apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: bidrag  
  name: bidrag-bidragskalkulator-v2
  namespace: bidrag
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "25" # 25 requester per minutt per nginx instance
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1" # optional, defaults to 1
    
spec:
  ingresses:
    - {{ INGRESS }}
      
  image: {{ image }}
  port: 3000
  env:
    - name: SERVER_URL
      value: {{SERVER_URL}}
    - name: ENVIRONMENT
      value: {{ENVIRONMENT}}
    - name: UMAMI_WEBSITE_ID
      value: {{UMAMI_WEBSITE_ID}}
    - name: INGRESS
      value: {{INGRESS}}
  envFrom: 
    - secret: bidragskalkulator-secrets
  accessPolicy:
    outbound:
      rules:
      - application: nav-dekoratoren
        namespace: personbruker
      - application: bidrag-bidragskalkulator-api
        namespace: bidrag
      external:
        - host: www.nav.no
        
  liveness:
    path: "/barnebidrag/tjenester/api/internal/isalive"
    initialDelay: 15
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/barnebidrag/tjenester/api/internal/isready"
    initialDelay: 15
    timeout: 1
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true