apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: bidrag
  name: bidrag-bidragskalkulator-v2
  namespace: bidrag

spec:
  ingresses:
    - https://bidragskalkulator-v2.intern.dev.nav.no
  image: bidrag-bidragskalkulator-v2
  port: 3000
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: dekoratoren.dev.nav.no
  liveness:
    path: "/api/internal/isalive"
    initialDelay: 15
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/api/internal/isready"
    initialDelay: 15
    timeout: 1