name: Bygg og deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@main
        id: docker-push-dev
        with:
          team: bidrag
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
      - name: Deploy til nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push-dev.outputs.image }}
          RESOURCE: .nais/naiserator.yml
          VARS: .nais/dev.json
