name: Kjør ende-til-ende-tester
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Sett opp Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "23"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@navikt"

      - name: Installer avhengigheter
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Installere headless-nettleser
        run: npx playwright install --with-deps
      - name: Kjør ende-til-ende-tester
        run: npm run test:e2e:mock
        env:
          BIDRAG_BIDRAGSKALKULATOR_TOKEN: "token"
      - name: Opprett rapport
        uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
