name: Kjør ende-til-ende-tester
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Installer avhengigheter
        run: npm ci
      - name: Installere headless-nettleser
        run: npx playwright install --with-deps
      - name: Kjør ende-til-ende-tester
        run: npm run test:e2e
      - name: Opprett rapport
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
